---

- name: get osp facts
  roles:
    - osp-facts
    
- name: configuration
  hosts: all
  # gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - configuration

- name: deploy haproxy
  hosts: frontends
  # gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - haproxy 

- name: deploy postgres
  #gather_facts: false
  become: true
  hosts: appdbs
  roles:
    - geerlingguy.postgresql

- name: deploy apache
  #gather_facts: false
  become: true
  hosts: apps
  roles:
    - tomcat

