
- hosts: jumpbox
  gather_facts: false
  vars:
    webserver_name: web1
    databaseserver_name: db1
    flavor_name: m1.small
    webserver_group: webservers
    database_group: databaseservers
    deployment: dev
  tasks:
  - name: Create a server instance
    os_server:
      cloud: ospcloud
      name: "{{ item }}"
      state: absent
    with_items:
      - app1
      - app2
      - db
      - frontend
#      image: rhel-guest
#      meta: "group={{ webserver_group }},deployment_name={{ deployment }}"
#      flavor: "{{ flavor_name }}"
#      security_groups: ICMP_and_SSH
#      key_name: ansible_ssh
#      nics:
