
- hosts: jumpbox
  gather_facts: false
  tasks:
  - name: Create a server instance
    os_server:
      cloud: ospcloud
      name: "{{ item }}"
      state: absent
    with_items:
      - app1
      - app2
      - db
      - frontend
      - web1
      - appdb1
