---

- hosts: jumpbox
  vars_files:
   - ./osp_create_param.yml
  become: yes
  roles:
     - osp-keypair
     - osp-securitygroup
     - osp-network
  tasks:
##Create Fronend Instance
  - name: Create  instance
    include_role: 
       name: osp-instances
    with_items: "{{ item1 }}"
  - name: Gather facts
    include_role: 
       name: osp-facts
    tags:
     - test_inventory