---

- hosts: jumpbox
  vars_files:
   - ./osp_create_param.yml
  become: yes
  roles:
     - osp-network
     - osp-keypair
     - osp-securitygroup
     - osp-flavor
  tasks:
##Create Fronend Instance
  - name: Create frontend instance
    include_role: 
       name: osp-facts
    with_items: "{{ item1 }}"
  - name: Gather facts
    include_role: 
       name: osp-facts